ministryofjustice/hmpps-manage-supervisions-prototype

app/views/new-service-user/v5/attendance-add-8.html, app/views/new-service-user/v5/notes-add.html, lib/extensions/_extensions.scss, package-lock.json
Added a page to confirm compliance and choose next steps
=> I added a confirmed compliance page

app/views/new-service-user/v5/progress.html
Updating the office visit from 8 Feb to 1 Mar for testing
=> change-appointment-date

app/views/new-service-user/v5/timeline.html
Updating 8 Feb to 1 Mar for testing
=> Change summary date

app/views/new-service-user/v5/timeline-confirm.html
Changed all the dates to the 1 March
=> changed-3-dates

app/views/new-service-user/v5/attendance-add-4.html
Changed date to 1 March for testing
=> Engagement-date-change

app/views/new-service-user/v5/attendance-add.html
Changed date from 8 Feb to 1 Mar for testing
=> change-attendance-date

app/views/new-service-user/v5/timeline.html
Changed date to 1 March from 8 Feb for testing (confirm attendance journey)
=> change-date-confirm-attendance

app/views/v6/appointment-update-3.html
Removed the 'with Dylan' part of the question to be consistent with the 'arrange session' journey
=> rearrange-updated-question

app/views/v6/appointment-update-2.html
Changed question to be consistent with the 'arrange session' journey so it's now 'What type of session would you like to arrange?
Removed the 'group session' radio button
=> rearrange-wording-changes

app/views/v6/attendance-add-7.html
Changed the labels so that they're not in question format:
Dylan's compliance
Reason for not complying
Dylan's engagement
=> label-updates

app/data/case-list-data.json, app/views/includes/case-list-data.html, lib/utils.js, server.js
This approach loads a JSON file into the nunjucks templating environment, making it easy to grab the data in the templates. It's built currenly just for the case load page, so the datafile will want generalising as it's extended, but the approach is proven, at least.
=> Load page data from files

app/assets/javascripts/application.js, app/assets/javascripts/autocomplete.js, app/data/case-list-data.js, app/filters.js, server.js
[Standard.js](https://standardjs.com/index.html) is the JS standard coding style. We already have the `standard` library as a developer dependency in the project but not all JS files in the project meet the standard.
It can be run on the command line with `npx standard` to show the violations, or `npx standard --fix` to auto-correct many of the violations. Some need to be fixed manually.
- Auto-fix violations using `standard`
- Remove unnecessary duplication in the auto-complete code
- Remove unused consts in the filters code
I've deliberately omitted `routes.js` to avoid creating a merge conflict with #87. The version of `routes.js` on that branch passes linting.
=> Make the JS code more compatible with Standard.JS

app/views/includes/case-list-data.html, app/views/v6/plan.html, app/views/v6/timeline-b.html, app/views/v6/timeline-entry-call.html, app/views/v6/timeline.html
This makes the page markup a bit cleaner.
=> Use GOV.UK Design System tag macros to define badges

app/data/nsi.js
NSI reference data for London NPS and London CRC. I've included both for contrast, and as Andrew suggested the structure might be more like the CRC data.
JSON generated using the following query:
```
SELECT JSON_objectAGG(pa.code value json_object(pa.description, 'nsiTypes' value JSON_objectAGG(c.code value c.nsiType RETURNING CLOB)RETURNING CLOB) RETURNING CLOB)
FROM PROBATION_AREA pa
INNER JOIN (SELECT json_object(rnt.description, st.nsiSubTypes) AS nsiType, rnt.CODE, RNTPA.PROBATION_AREA_ID 
FROM R_NSI_TYPE rnt 
INNER JOIN R_NSI_TYPE_PROBATION_AREA rntpa ON RNTPA.NSI_TYPE_ID = RNT.NSI_TYPE_ID
INNER JOIN R_RQMNT_NSI_TYPE rrnt ON rrnt.NSI_TYPE_ID = rnt.NSI_TYPE_ID 
INNER JOIN R_RQMNT_TYPE_MAIN_CATEGORY rrtmc ON rrtmc.RQMNT_TYPE_MAIN_CATEGORY_ID = rrnt.RQMNT_TYPE_MAIN_CATEGORY_ID 
left …
```
=> Initial stab at NSI reference data

app/views/prototype/arrange-a-session/session-add-3.html, lib/helpers.js
Move the RAR categories into a JavaScript helper. This is a step towards making the list more dynamic.
=> Move RAR categories into a helper

app/views/prototype/arrange-a-session/session-add-4.html
=> Use summary list macro to reduce markup

lib/helpers.js
This error means the prototype is currently crashing
=> Fix syntax error

app/data/cases.js, app/utils/confirm-attendance-wizard-paths.js, app/views/confirm-attendance/check.html, app/views/confirm-attendance/rar-categories.html, app/views/confirm-attendance/rar.html
* Add RAR subcategories when confirming appointments
* Put the category/subcategory choice on a separate page from the Yes/No RAR question
* Fix some branching bugs in the wizard routing
=> Make RAR pages consistent between 'arrange an appointment' and 'confirm attendance'

app/data/cases.js, app/routes/cases.js, app/utils/confirm-attendance-wizard-paths.js, app/views/arrange-a-session/_session-details.html, app/views/case/_appointment-timeline-entry.html, app/views/case/appointment.html, app/views/confirm-attendance/_outcome-details.html, app/views/confirm-attendance/check.html
The appointment links on the 'communication' list now work.
=> Appointment details page

app/views/case/index.html, app/views/case/sentence.html
=> Show unpaid work on the quick look and sentence pages

app/views/case/details.html, app/views/case/personal-details.html
Best reviewed [by ignoring whitespace](https://github.com/ministryofjustice/hmpps-manage-supervisions-prototype/pull/155/files?diff=split&w=1).
=> Show 'none known' when no aliases present

app/views/case/index.html
=> Quick look: correctly render the case when there are no next appointments

app/data/cases.js, app/views/case/_case-documents.html, app/views/case/details.html, app/views/case/sentence.html
=> Show documents as unavailable if they are missing

app/routes/cases.js, app/views/case/_communication-timeline-entry.html, app/views/case/other-communication.html
=> Add an 'other communications' page

app/data/cases.js, app/views/case/_case-service-user-banner.html
This changes allows us to show different risk badges for different service users.
=> Make risk badges dynamic for Dylan

app/data/cases.js, lib/helpers.js
This change makes it easier to align the sentence start and end dates.
=> Make it easier to calculate sentence end dates

app/data/cases.js
* Add initial import of data for Spencer
* Fix a few places in the app which didn't display Spencer's information correctly:
* show all requirements including unpaid work
* only show the next appointment block if there is one
=> Add data for Spencer

app/data/cases.js
We don't need this service user for the model office.
=> Remove unnecessary service user

app/views/case/communication.html
Works almost identically to emails and text messages to/from the service user.
=> Display unplanned phone calls on the communication page

app/views/arrange-a-session/when.html, app/views/case/details.html, app/views/case/index.html, app/views/case/personal-details.html
Similar to the case when there are no known aliases.
=> Display 'none known' when there are no known disabilities and adjustments

app/data/cases.js, app/views/case/_communication-timeline-entry.html, app/views/case/communication.html, app/views/case/other-communication.html
=> Show notes as part of the 'other communication' section on the comms page

app/assets/javascripts/autocomplete.js, app/routes.js, app/routes/add-other-communication.js, app/routes/cases.js, app/utils/add-other-communication-wizard-paths.js, app/views/add-other-communication/check.html, app/views/add-other-communication/confirmation.html, app/views/add-other-communication/new.html, app/views/case/add-communication.html, app/views/case/communication.html, lib/helpers.js
This doesn't quite match the design yet:
* the 'routing' page is incomplete (missing the ability to arrange appointments or add appointment notes)
* ~it's impossible to choose other days (apart from today) yet~ this is now possible
* ~it's impossible to specify other recipients and senders yet~ this is now possible
=> Add other communication

app/data/session-data-defaults.js
=> Set the provider and team for Model office 1

app/routes/cases.js, app/views/arrange-a-session/_session-details.html, app/views/case/appointment-notes.html, app/views/case/appointment.html, app/views/confirm-attendance/_outcome-details.html
Allow editing of appointment notes.
=> Edit appointment notes

app/routes/cases.js, app/views/case/add-communication.html, app/views/case/communication.html, app/views/case/which-appointment-to-add-notes-to.html, lib/helpers.js
=> Add an appointment note

app/data/cases.js, app/routes.js, app/views/cases/_case-list-data.html, app/views/cases/index.html, lib/helpers.js
To unhide a hidden service user, access:
`/show-case/<CRN>`
=> Hide Gary by default, add an endpoint for unhiding service users when needed

app/routes/cases.js, app/views/case/add-communication.html, app/views/case/appointment-notes.html
=> Update microcopy around appointment notes based on feedback

app/views/add-other-communication/new.html, app/views/arrange-a-session/index.html, app/views/includes/moj-header.html, app/views/index.html, app/views/sign-in.html, lib/helpers.js
- Let users enter first name, last name and team
- Show name in header, and use values as "lastUpdatedBy" eg when creating appointments, and as "You" in new communications
- Default to Mark B when no details given
This does not update all references to Mark B in the cases file.
=> Add sign in page

app/data/cases.js
https://trello.com/c/eVXO191A/442-last-minute-front-end-changes-before-model-office
=> Tweaks for model office

lib/helpers.js
This reverts commit a4f4236f684ef8167c41fb4062d4c8bb242a4620.
The way it worked before was correct.
=> Revert "An appointment is the next until its start time has passed"

lib/helpers.js
=> Fix the 'confirm appointment' selection screen

app/views/case/appointment.html, package-lock.json
=> Allow confirming attendance on the appointment detail page, before the appointment

app/data/cases.js
Broken 'confirm attendance' flow for Gary, which also corrupted Gary's communication data.
Using low-index, numerical sessionIds breaks some of the helper code
for setting session data. Switching to alphanumerical IDs sorts the problem.
=> Change the 'sessionIds' for Gary's contactHistory

app/models/arranged-session.js, app/views/arrange-a-session/_session-details.html
=> Arranging repeat appointments: display on the 'check' page

app/views/case/details.html, app/views/to-delius.html
https://trello.com/c/qhbkCPwH/350-link-to-delius-on-the-contact-details-screen
| Change links | Change link destination |
|--|--|
| ![Screen Shot 2021-05-04 at 14 56 19](https://user-images.githubusercontent.com/319055/117014914-2dc25500-ace9-11eb-8bb9-022d0b866f56.png) | ![Screen Shot 2021-05-04 at 14 56 25](https://user-images.githubusercontent.com/319055/117014923-2f8c1880-ace9-11eb-8af4-2e5e8a8b07e5.png) |
=> Link to National Delius for changing contact details

app/views/case/_case-nav.html, app/views/case/index.html
Move content from right column into main column, and visually space items.
| Before | After |
|--|--|
| ![manage-supervisions herokuapp com_cases_J678910](https://user-images.githubusercontent.com/319055/117149218-ee5e3c00-adae-11eb-82ba-a74a15ab6e22.png)|![localhost_3002_cases_J678910](https://user-images.githubusercontent.com/319055/117149205-eacab500-adae-11eb-8869-674e784f417f.png) |
=> Balance Quick look page columns

app/data/cases.js, app/views/confirm-attendance/_outcome-details.html, app/views/confirm-attendance/absence-acceptable.html, app/views/confirm-attendance/check.html, app/views/confirm-attendance/non-compliance-reason.html
=> Show missing options when confirming attendance and recording absence

app/routes/arrange-a-session.js, app/routes/cases.js, app/routes/confirm-attendance.js, app/views/arrange-a-session/_session-details.html, app/views/arrange-a-session/cancel-confirmation.html, app/views/arrange-a-session/check.html, app/views/arrange-a-session/confirmation.html, app/views/arrange-a-session/rar-categories.html, app/views/arrange-a-session/when.html, app/views/case/appointment.html, app/views/confirm-attendance/_outcome-details.html, app/views/confirm-attendance/check.html, app/views/confirm-attendance/confirmation.html, app/views/confirm-attendance/rar-categories.html, app/views/confirm-attendance/start.html
As per feedback here: https://github.com/ministryofjustice/hmpps-manage-supervisions-prototype/pull/206#discussion_r626530958
=> Simplify wizard templates using an 'appointment' local variable

app/views/case/_appointment-timeline-entry.html, app/views/case/_communication-timeline-entry.html, app/views/case/communication.html
| Before | After |
| -- | -- |
|![manage-supervisions herokuapp com_cases_J678910_communication](https://user-images.githubusercontent.com/319055/117666055-5dff6d00-b19b-11eb-9573-e7a596c0b77b.png) |![localhost_3002_cases_J678910_communication (1)](https://user-images.githubusercontent.com/319055/117666147-7a030e80-b19b-11eb-9c30-a1878a2d1eb0.png) |
=> Condense communications timeline

app/data/cases.js, app/views/case/address-book-personal.html, app/views/case/index.html, app/views/confirm-attendance/check.html
- Updating the H1 and button content on the check your answers page for confirming details
- Updated Risk content on the Overview page 
- Added phone numbers for personal contacts
- Updated SU data
=> Content quick changes may 10

app/views/arrange-a-session/notes.html, app/views/confirm-attendance/notes.html
https://mojdt.slack.com/archives/C6C1KGRME/p1614773164001800
=> Fix NDelius branding

app/views/case/address-book-personal.html, app/views/case/address-book-professional.html
- Add change links to personal and professional contacts which links to the page to send them to nDelius.
=> Add change links to contacts

app/data/cases.js
Made various content changes based on the feedback from the last model office, removing the hostel information.
=> changes to Dylan's content

app/routes/add-other-communication.js, app/views/add-other-communication/email/check.html, app/views/add-other-communication/email/confirmation.html, app/views/add-other-communication/email/receiver.html, app/views/add-other-communication/email/when.html, app/views/add-other-communication/phone-call/check.html, app/views/add-other-communication/phone-call/confirmation.html, app/views/add-other-communication/phone-call/receiver.html, app/views/add-other-communication/phone-call/when.html, app/views/add-other-communication/text/check.html, app/views/add-other-communication/text/confirmation.html, app/views/add-other-communication/text/receiver.html, app/views/add-other-communication/text/when.html, lib/helpers.js
=> Use the 'memorable date' pattern when adding an email/text/phone call

app/data/session-data-defaults.js
Merge between the model offices.
=> MO4 team update

app/data/reference/circumstance-types.json
Query:
```
SELECT json_objectagg(pa.CODE value json_object(pa.DESCRIPTION, 'circumstanceTypes' value json_objectagg(t.CODE_VALUE value t.circType returning clob) returning clob)returning clob)
FROM PROBATION_AREA pa
INNER JOIN (SELECT json_object('description' value rct.CODE_DESCRIPTION, 'allowDuplicates' value rct.ACTIVE_DUPLICATES, 'enquiry' value rct.ENQUIRY, 'circumstanceSubtypes' value st.circSubType returning clob) AS circType, rct.CODE_VALUE, rctp.PROBATION_AREA_ID 
FROM R_CIRCUMSTANCE_TYPE rct 
INNER JOIN R_CIRCUMSTANCE_TYPE_PROVIDER rctp ON rctp.CIRCUMSTANCE_TYPE_ID = rct.CIRCUMSTANCE_TYPE_ID
INNER JOIN( SELECT json_objectagg(rcst.CODE_VALUE value json_object('description' value rcst.CODE_DESCRIPTION returning clob) returning clob) AS circSubType, rcts.CIRCUMSTANCE_TYPE_ID
FROM …
```
=> Add circumstance type data from test

app/models/outcomes.js, app/views/confirm-attendance/absence-acceptable.html, lib/helpers.js
- Move the 'Other' option to the bottom of the list
- Drive the radio buttons off the NDelius outcomes reference data and try to document the removal of certain options with code comments
=> Drive the 'acceptable reasons for absence' off the NDelius data

app/utils/confirm-attendance-wizard-paths.js, app/views/confirm-attendance/absence-acceptable.html, app/views/confirm-attendance/absence-reason.html
=> Reasons for acceptable absence on a separate page

app/views/add-other-communication/email/sensitive.html, app/views/add-other-communication/phone-call/sensitive.html, app/views/add-other-communication/text/sensitive.html, app/views/arrange-a-session/sensitive.html, app/views/confirm-attendance/sensitive.html, app/views/includes/sensitive-guidance.html
=> Add guidance to the sensitive contact pages

app/views/arrange-a-session/add-notes.html, app/views/arrange-a-session/notes.html, app/views/arrange-a-session/rar-categories.html, app/views/arrange-a-session/rar.html, app/views/confirm-attendance/add-notes.html, app/views/confirm-attendance/compliance.html, app/views/confirm-attendance/index.html, app/views/confirm-attendance/non-compliance-reason.html, app/views/confirm-attendance/notes.html, app/views/confirm-attendance/rar-categories.html, app/views/confirm-attendance/rar.html
Nothing will be saved to Delius until the final confirmation step is completed. As nothing is persisted, Continue is more accurate.
=> Switch from "Save and continue" to "Continue"

app/data/cases.js
This is done to avoid leaving large gaps in the activity log.
It's meant re-writing one of the entries to remove references to New Year and Christmas.
=> Make Gary's activity log dynamic

app/views/case/activity-log.html, app/views/case/address-book-personal.html, app/views/case/address-book-professional.html, app/views/case/appointment.html, app/views/case/details.html, app/views/case/flag.html, app/views/case/flags.html, app/views/case/index.html, app/views/case/personal-details.html, app/views/case/previous-orders.html, app/views/case/schedule.html, app/views/case/sentence.html
Back links aren't working so well now there are multiple places something can be accessed from. My using breadcrumbs we instead say "this lives here", and there's some degree of orientation.
=> Use breadcrumbs rather than back links

app/assets/sass/application.scss, app/data/generators/case.js, app/data/generators/risk.js, app/data/reference/risk-flags.json, app/views/_components/risk-flag/macro.njk, app/views/_components/risk-flag/template.njk, app/views/case/_case-service-user-banner.html, app/views/case/flags.html, app/views/case/index.html, app/views/layout.html
- Import registrations data from Delius (via https://docs.google.com/spreadsheets/d/1YWiDn22gRsujF2R86geWrgvr1f3R7a85-Qyi5OO34o4/edit#gid=1535497460)
- Use new flag data in generated cases
- Sort flags alphabetically
- Create a component for displaying risk flags
- Tweak styles of tags for better display on multiple lines
=> Show many flags on generated cases

app/data/cases.js, app/views/case/details.html, app/views/case/disabilities-and-adjustments.html
- Include titles of adjustments in summaries (comma separated list)
- Be explicit when there are no adjustments
- Add disability and adjustment end dates
=> Show adjustments when summarising disabilities

app/data/cases.js, app/data/generators/case.js, app/data/generators/full-addresses.js, app/views/case/_address.html, app/views/case/addresses.html, app/views/case/details.html
https://ms-design-history.herokuapp.com/all-addresses/
=> Add page for all addresses

app/assets/sass/application.scss, app/data/cases.js, app/data/generators/risk.js, app/views/_components/risk-flag/template.njk, app/views/case/index.html, app/views/cases/_case-list-data.html
- ROSH statuses can be Very high, High, Medium or Low
- Add a very high status which is dark red
- Switch medium from orange to yellow for better differentiation with high
=> Very High ROSH

app/views/_components/risk-flag/template.njk, app/views/case/risk/_risk-in-the-community.html
Serious harm is different. The distinction is important.
=> Risk of serious harm, not Risk of harm

app/data/reference/offences.json
Query:
```
SELECT JSON_objectAGG(main_category_code value json_object('description' value main_category_description, 'offences' value json_objectagg(CODE, description RETURNING CLOB) RETURNING CLOB) RETURNING CLOB) FROM R_OFFENCE ro
WHERE SELECTABLE = 'Y'
GROUP BY main_category_code, main_category_description
ORDER BY MAIN_CATEGORY_CODE, CODE
```
Sorted with 
```
cat offences.json | jq --sort-keys 'walk(if type == "array" then sort else . end)' > offences2.json
```
=> Add offence categories and offences reference data
