ministryofjustice/hmpps-manage-supervisions-prototype

app/views/new-service-user/v5/attendance-add-8.html
Removed the date from the compliance confirmation screen (should save us from having to update this in other iterations)
=> removed-date-compliance-confirmation

app/views/includes/navigation.html, app/views/v6/details.html, app/views/v6/plan.html, app/views/v6/progress.html, app/views/v6/sentence.html, app/views/v6/timeline.html
This only replaces the nav for the main 5 pages.
There's lots of training whitespace in these files, if you want to ignore those changes, use this link:
https://github.com/ministryofjustice/hmpps-steel-thread/pull/86/files?diff=split&w=1
=> Make the navigation component reusable

app/data/case-list-data.js, app/filters.js, app/views/includes/case-list-data.html, package-lock.json, package.json, server.js
Changes:
- turn the JSON data into a JS file, which will allow DSLs when defining the test data (e.g. putting dates n days in future)
- store the appointment date as a date, and move the formatting into a filter
=> Separate storage and presentation when rendering appointment dates

app/assets/javascripts/autocomplete.js
There are JS errors on the console on pages that don't have the autocomplete elements (start and end time fields).
Only attempt applying the autocomplete when the relevant elements are present on the page.
=> Only apply autocomplete on pages with appropriate elements

app/data/cases.js, lib/helpers.js, package-lock.json, package.json
User research participants notice it when test data dates are inconsistent (e.g. upcoming appointments are in the past). Previously we've had to [update test data prior to testing](https://github.com/ministryofjustice/hmpps-steel-thread/pull/97) to ensure believability.
Introduce some helper functions which allow specifying a timestamp that's:
* today
* tomorrow
* `x` days in the future
This change also adds a `luxon` plugin called `luxon-business-days` which helps avoid appointment dates that fall on the weekends.
=> Allow auto-updating relative timestamps in the test data

app/models/rar-categories.js, app/routes.js
We weren't mapping to quite the right contact type before, and it wasn't possible to record RARs against the old one in all cases.
=> Use alternative office visit contact type

app/data/cases.js, app/data/session-data-defaults.js, app/routes/confirm-attendance.js, app/utils/confirm-attendance-wizard-paths.js, app/utils/wizard-helpers.js, app/views/case/timeline.html, app/views/confirm-attendance/absence-acceptable.html, app/views/confirm-attendance/add-notes.html, app/views/confirm-attendance/check.html, app/views/confirm-attendance/compliance.html, app/views/confirm-attendance/confirmation.html, app/views/confirm-attendance/non-compliance-reason.html, app/views/confirm-attendance/notes.html, app/views/confirm-attendance/rar-categories.html, app/views/confirm-attendance/start.html
* Use Nunjucks macros where possible
* Add CRN and a session ID into the URL to enable confirming attendance for multiple appointments
* Update visual design to be in line with the 'arrange a session' flow
* Update the routing to use the new wizard routing, which allows for consistent back links
* De-duplicate the template markup by using the wizard form template
=> Tidying confirm attendance flow (part 5)

app/assets/sass/application.scss, app/assets/sass/components/_cases-table.scss, app/assets/sass/components/_key-details-bar.scss, app/assets/sass/components/_time-autocomplete.scss, app/assets/sass/govuk-page-masthead.scss, app/assets/sass/max-widths.scss, app/views/arrange-a-session/when.html, app/views/includes/case-list-data.html
- Remove any unused styles
- Move groups of styles into separate files (components or otherwise)
- Remove dangerously generic style rules that could accidentally apply in unintended places
- Begin using govuk-frontend variables rather than hardcoded colours and fonts
=> Clean up of application.scss

app/data/cases.js, app/views/case/_case-service-user-banner.html, app/views/case/details.html, app/views/case/personal-details.html, app/views/includes/service-user-banner.html, app/views/index.html, lib/helpers.js
The service user's age was off because the values were hard-coded.
=> Make the service user's age calculated dynamically from the DOB

app/data/cases.js, app/data/session-data-defaults.js, app/views/confirm-attendance/check.html, app/views/confirm-attendance/confirmation.html, app/views/confirm-attendance/rar-categories.html, app/views/confirm-attendance/start.html, lib/helpers.js
This is a step towards having fully consistent data in the prototype.
=> Unify how 'confirm attendance' and 'arrange an appointment' data is stored (part 1)

app/assets/sass/application.scss, app/assets/sass/components/_app-card-meta-list.scss, app/views/case/_case-service-user-banner.html
The height of the key details banner has been reduced. 
The layout change has been taken from digital products in prison. 
Before:
After:
=> Update key details banner layout

app/assets/sass/application.scss, app/assets/sass/components/_app-card-one-third-column-list.scss, app/views/case/details.html, app/views/case/index.html, app/views/case/sentence.html
- Update the definition lists on the Quick look page:
Before:
After:
- Removed Recent communication from the Quick look page
- Added Probation status to Quick look page
- Content tweaks to Quick look, Personal details and Sentence pages for consistency.
=> Update styling of definition list

app/data/cases.js, app/data/session-data-defaults.js, app/routes/arrange-a-session.js, app/utils/arrange-a-session-wizard-paths.js, app/utils/confirm-attendance-wizard-paths.js, app/views/arrange-a-session/_session-details.html, app/views/arrange-a-session/cancel-confirmation.html, app/views/arrange-a-session/check.html, app/views/arrange-a-session/confirmation.html, app/views/arrange-a-session/index.html, app/views/arrange-a-session/rar-categories.html, app/views/arrange-a-session/rar.html, app/views/arrange-a-session/rearrange-or-cancel.html, app/views/arrange-a-session/when.html, app/views/arrange-a-session/where.html, app/views/case/_appointment-timeline-entry.html, app/views/case/communication.html, app/views/case/index.html, app/views/cases/_case-list-data.html, app/views/confirm-attendance/absence-acceptable.html, app/views/confirm-attendance/add-notes.html, app/views/confirm-attendance/check.html, app/views/confirm-attendance/compliance.html, app/views/confirm-attendance/confirmation.html, app/views/confirm-attendance/non-compliance-reason.html, app/views/confirm-attendance/notes.html, app/views/confirm-attendance/rar-categories.html, app/views/confirm-attendance/start.html, app/views/includes/ndelius-record-details.html, lib/helpers.js
* Show future appointments in the 'communication' view
* The next appointment is calculated dynamically
* Arranging an appointment makes it appear in the communication list and in the next appointment block if it's the next one
=> Unify the data in the prototype, make it persist between transactions

app/assets/sass/components/_app-card-meta-list.scss, app/assets/sass/components/_app-card-one-third-column-list.scss
Update meta list and 2/3rds column list styles to use built in mixins and DRY up code.
=> Switch styles to use govuk-frontend mixins

app/filters.js, app/views/confirm-attendance/_outcome-details.html, app/views/confirm-attendance/notes.html
* Allow multiple files to be uploaded
* Save the filenames of the files being uploaded
* Show links to those files on the check your answers and previous appointment pages
No files are actually uploaded.
https://trello.com/c/mhbdraah/420-make-the-upload-file-button-functional
=> Show uploaded files in outcome details

app/views/cases/index.html
=> Display the real "recently allocated case" number instead of hard-coded number

app/views/case/_appointment-timeline-entry.html, app/views/case/_communication-timeline-entry.html, app/views/case/address-book-professional.html, app/views/case/communication.html
| Before | After |
|--|--|
| ![Screen Shot 2021-04-21 at 17 03 06](https://user-images.githubusercontent.com/319055/115585456-880fee80-a2c3-11eb-9df8-139ef2da0fb5.png) |  ![Screen Shot 2021-04-21 at 17 02 43](https://user-images.githubusercontent.com/319055/115585453-86dec180-a2c3-11eb-80f0-a8e4542f87e3.png) |
Also includes a fix for the red banner showing on a grey box:
=> Make timeline a little easier to scan

app/views/case/_appointment-timeline-entry.html, app/views/case/appointment.html, lib/helpers.js
Time-related bug-fixes:
- the prompt to confirm an appointment should appear as soon as the start time has passed
- on the Communication page
- on the appointment details page
- treat all times as local time (rather than GMT/UTC) to avoid unexpected behaviour during the BST months
- sort upcoming appointments by their start time, not by their end time (🤦 )
=> Time-related bug-fixes

app/routes/cases.js, app/routes/confirm-attendance.js, app/utils/confirm-attendance-wizard-paths.js, app/views/add-other-communication/new.html, app/views/case/add-communication.html, app/views/confirm-attendance/index.html, lib/helpers.js
Extend the 'Add communication' screen to allow recording appointment outcomes:
=> Add a thing flow: recording appointment attendance

app/utils/arrange-a-session-wizard-paths.js, app/views/arrange-a-session/_session-details.html, app/views/arrange-a-session/add-notes.html, app/views/arrange-a-session/check.html, app/views/arrange-a-session/notes.html, app/views/arrange-a-session/rar-categories.html, app/views/arrange-a-session/rar.html, app/views/confirm-attendance/_outcome-details.html, app/views/confirm-attendance/add-notes.html, app/views/confirm-attendance/notes.html, app/views/confirm-attendance/rar-categories.html, app/views/confirm-attendance/rar.html
**Before:**
**After:**
**Before**
**After**
**Before**
**After**
(I moved the `details` to under the `textarea` as a quick fix)
This was a speculative issue, we thought users may then the green button saying 'Arrange appointment' may be thought as starting a new transaction, but it may be best to test if this is a real concern. 
**Before**
**After**
This was to try and avoid using questions in the labels, and for consistency between the two transactions
**Before**
Arrange an appointment
Confirm attendance
**After**
Arrange an appointment 
Confirm attendance
We discussed replacing content of 'Calendar note' with 'Appointment notes' and making it consistent with confirming attendance. However, I've removed the `details` about CRISS as it's not relevant before an appointment, and I've also …
=> Add calendar note page

app/routes/cases.js, app/views/case/appointment.html, app/views/layout.html, package-lock.json, package.json, server.js
Display a banner to confirm that the user has successfully updated the appointment notes:
- Update `govuk-frontend` to v3.11 in order to pick up the [notifications banner component](https://design-system.service.gov.uk/components/notification-banner/)
- Add the `connect-flash` package, which introduces flash middleware into the app
- Wire in the success banner on the appointment page
Do we need this functionality at all?
Is the banner displayed in the right place on the page?
=> Show success flash after editing appointment notes

app/data/cases.js, app/views/case/_appointment-timeline-entry.html, app/views/case/_communication-timeline-entry.html, app/views/case/appointment.html, app/views/case/communication.html, app/views/case/other-communication.html, lib/helpers.js
- Assume "Mark Berridge" is the default, and replace with the current user's name if available
- Do not replace other names, for example Sally Smith, who is someone else that has worked on Gary's case
- Remove "Mark" from contents of communications and appointments
=> Show current user's name in communications and appointments

app/routes/add-other-communication.js
All the cases were defaulting to Dylan.
By putting the `router.all` lower down in the order of routes, not all page paths were hitting the middleware, meaning some pages were not finding the case based on CRN, and so were using the wrong case.
=> Show the right case names when adding phone/text/email

lib/helpers.js
Before this change, an appointment was the next one until its end time had passed.
=> An appointment is the next one until its start time has passed

app/models/arranged-session.js, app/routes/arrange-a-session.js, app/utils/helpers.js
* change the 'random' function to be random when called several times in quick succession
* when an appointment is arranged that's supposed to be repeating, add 3 additional future weekly repeat appointments, booked on the same day of the week and at the same time:
The repeat appointments aren't reflected on the 'confirmation' page – should it say anything different?
=> Insert multiple repeat appointments

app/utils/add-other-communication-wizard-paths.js, app/views/add-other-communication/email/check.html, app/views/add-other-communication/email/sensitive.html, app/views/add-other-communication/phone-call/check.html, app/views/add-other-communication/phone-call/sensitive.html, app/views/add-other-communication/text/check.html, app/views/add-other-communication/text/sensitive.html, app/views/case/_communication-timeline-entry.html, app/views/case/other-communication.html
https://trello.com/c/RS3e1OuZ/464-prototype-ability-to-mark-and-view-sensitive-comms
| Feature | Screenshot |
|--|--|
| Asking if sensitive | ![Screen Shot 2021-05-04 at 16 04 28](https://user-images.githubusercontent.com/319055/117029339-75031280-acf6-11eb-921c-68bf2b471bdc.png) |
| Check answers| ![Screen Shot 2021-05-04 at 15 38 55](https://user-images.githubusercontent.com/319055/117029409-851af200-acf6-11eb-85b3-22aa16cc853f.png) |
| Showing a sensitive communication | ![Screen Shot 2021-05-04 at 15 49 55](https://user-images.githubusercontent.com/319055/117029400-83512e80-acf6-11eb-89cd-517907d82c91.png) |
| Showing a sensitive communication (own page) | ![Screen Shot 2021-05-04 at 16 32 52](https://user-images.githubusercontent.com/319055/117029403-83e9c500-acf6-11eb-8d89-0cf41cf7a2 …
=> Ask if a communication is sensitive

app/models/arranged-session.js
A side-effect of this change is that the date is no longer defaulted
if some part of the date is missing.
=> Use luxon to reconstruct date from year, month and day

app/models/arranged-session.js
This bug was introduced in #218
=> Fix Invalid Date error when arranging appointments

app/views/confirm-attendance/_outcome-details.html
There was a bug that was preventing the change link from appearing on the 'Check' page when confirming attendance.
=> Confirm attendance journey: make the 'sensitive' change link

app/data/cases.js, app/models/outcomes.js, app/views/confirm-attendance/_outcome-details.html, app/views/confirm-attendance/non-compliance-reason.html, lib/helpers.js
The original designs for capturing reasons for non-compliance allowed free-text, which doesn't fit in with NDelius's way of recording appointment outcomes.
The new design is driven off NDelius's reference data and is an initial attempt that is technically implementable. We will collect user feedback on this design to see if we need to provider more/other options.
Before:
After:
=> Capture only structured reasons for non-compliance

app/models/arranged-session.js
This bug was introduced in #218.
=> Fix another "Invalid DateTime" when showing appointments

app/views/confirm-attendance/absence-acceptable.html, app/views/confirm-attendance/compliance.html
Research has shown users find the current compliance question unclear:
We have improved the content so that choices are now more clearly explained:
And temporarily added hint text for the types of acceptable absences, which we will turn into structured options in the future:
=> Update confirm absence content

app/data/cases.js, app/views/case/sentence.html
- Replaced 'Rehabilitation Activity Requirement (RAR) with 'RAR'
**Why** - RAR is a well understood term, space is limited, and the term can be further defined elsewhere in the product
- Removed length of sentence
**Why** - It's repeated in the length section and time elapsed section, so there is no need to display it in the sentence title
- Moved offence and offence details to the top of the page
**Why** - Users want to be able to see the offence first, and it provides a more logical order to offence, sentence and requirements for users
=> Update sentence page layout

app/routes/arrange-appointment.js, app/utils/arrange-appointment-wizard-paths.js, app/views/arrange-appointment/check.html, app/views/arrange-appointment/repeating-preview.html
Show users the actual dates of repeat appointments before they confirm, so they know what appointments they are arranging.
| Page | Screenshot |
|--|--|
| Repeating? | ![Screen Shot 2021-05-25 at 10 23 53](https://user-images.githubusercontent.com/319055/119477900-47cee080-bd47-11eb-84d9-387aa5825dae.png) |
| Appointments being arranged | ![Screen Shot 2021-05-25 at 10 23 58](https://user-images.githubusercontent.com/319055/119477896-469db380-bd47-11eb-96b0-12c77928f0eb.png) |
| Check your answers | ![Screen Shot 2021-05-25 at 10 34 20](https://user-images.githubusercontent.com/319055/119477889-456c8680-bd47-11eb-8009-32bd67d0a8de.png) |
=> Show users the dates of repeat appointments

app/views/arrange-appointment/_appointment-details.html, app/views/case/appointment.html, app/views/confirm-attendance/_outcome-details.html, lib/helpers.js
- Sort list of future appointments in the schedule
- Use warning text component for recording attendance on appointment page
- Fix bug where notes weren't being hidden when an outcome was recorded
- Hide sensitive when outcome recorded, to avoid showing twice
- Default sensitive to No if no value set
- Update page title to match activity log title
| Before | After |
|--|--|
| ![manage-supervisions herokuapp com_cases_J678910_appointments_456](https://user-images.githubusercontent.com/319055/119521680-46b3a880-bd73-11eb-8f9a-fed802c989a9.png) | ![localhost_3005_cases_J678910_appointments_456 (1)](https://user-images.githubusercontent.com/319055/119521749-5632f180-bd73-11eb-97cd-0601948e7ea6.png) |
=> Appointment page bug fixes and design tweaks

app/data/cases.js, app/utils/confirm-attendance-wizard-paths.js, app/views/add-other-communication/phone-call/when.html, app/views/add-other-communication/text/when.html, app/views/arrange-appointment/confirmation.html, app/views/case/index.html, app/views/confirm-attendance/confirmation.html
- Add offence details to overview
- Make overview lists consistent with sentence and details pages
- Remove arrange appoint CTA as it's now in the schedule
- Remove rearrange appointment CTA - can do from appointment detail page
- Cleaned up the confirmation page after confirming attendance – remove CTA to arrange another appointment
- Changed wording of phone call and text journey
- Make Brian lower risk, adding contacts
Authored by @kelliedesigner
=> Quick wins

app/assets/sass/application.scss, app/data/cases.js, app/filters.js, app/routes/cases.js, app/views/case/_case-nav.html, app/views/case/_case-service-user-banner.html, app/views/case/flag.html, app/views/case/flags.html, app/views/case/index.html, package-lock.json, package.json
- Show list of flag details on overview
- Add risk flag tab
- Add risk pages
Includes:
- Adding more data to riskBadges in cases data (avoids refactoring that for now)
- Routing to individual flag pages
- Enables the design system's new link styles
- Experimental clickable-tag design
Notes:
- Only guidance for registered sex offender has been added so far
- No design for the ROSH flags yet
- Standard flag data, like categories and guidance needs to go somewhere
- No designs for seeing a flag's review
- No designs for reviewing a flag – probably deferred to Delius for MVP
| Case page | Risk flags | Risk flag |
| -- | -- | -- |
| ![localhost_3009_cases_E577913](https://user-images.githubusercontent.com/319055/120345378-56426c80-c2f2-11eb-9696-8d2f93c7c058.png) | …
=> Add initial pages for risk flags

app/data/cases.js
* To ensure we're not accidentally presenting more specific information that we have on record
* To gather evidence whether the reference data labels in Delius meet user need or need content design in our service
Trello: https://trello.com/c/PZPK9zLu/529-align-service-user-personal-circumstances-in-the-prototype-with-delius-reference-data
=> Align personal circumstances prototype data with Delius reference data

app/data/fake-cases.js, app/data/generators/address.js, app/data/generators/case.js, app/data/generators/current-order.js, app/data/generators/generator-helpers.js, app/data/generators/person.js, app/data/generators/personal-contact.js, app/data/generators/previous-orders.js, app/data/generators/professional-contact.js, app/data/generators/risk-flags.js, app/data/generators/risk.js, app/data/session-data-defaults.js, package-lock.json, package.json
Allow us to generate cases or aspects of a case quickly.
Make it easier to:
- test designs with higher data volume
- spin up new test cases for certain design criteria
- see how the design responds to a variety of data
Doesn't yet generate a contact history (just an initial appointment)
This PR will append 10 generated cases to the end of the case list.
=> Add the ability to generate fake cases in the prototype

app/views/case/_compliance-previous-orders.html
Following testing, we've changed this title to reflect that it's previous orders and not just those that were completed.
=> Changed "Completed orders" to "Previous orders"

app/data/cases.js, app/data/generators/personal-contact.js, app/routes/cases.js, app/views/case/details.html, app/views/case/personal-contact.html
- Add relationship type to personal details tab (and data)
- Create page for personal contacts
- Show extra Delius data in cases data
=> Create pages for personal contacts

app/data/cases.js, app/data/generators/risk.js, app/views/case/index.html
The service is dealing with community cases initially so custody risk isn't
relevant for those.
=> Remove 'In custody' risk column from overview page

app/data/cases.js, app/data/generators/risk.js
This data isn't relevant (and doesn't exist) for community cases.
=> Remove 'To prisoners' row in the RoSH risk table

app/data/cases.js, app/data/generators/case.js, app/data/generators/risk.js, app/data/reference/risk-flags.json, app/data/session-data-defaults.js, app/routes/cases.js, app/views/_components/risk-flag/template.njk, app/views/case/_case-service-user-banner.html, app/views/case/flag.html, app/views/case/flags.html, app/views/case/index.html, lib/helpers.js
Refactor risk flags so that:
- cases do not repeat risk flag text, instead they use the reference data
- risk of serious harm level is calculated based on the highest risk in the community data (as it is on live)
- use built in colours from Delius rather than our custom category colours
- remove all references to categories
- rename riskBadges to riskFlags
- use yellow not orange for risk flags to improve differentiation with red
> Remove categories, stick with alphabetical list
> Whilst 30% of participants said they were useful, and 46% of said they were “quite useful” there seems to be very little consensus on how to re categorise or improve the categories going forward. Suggest simplifying things for now by removing the categories and keep the flags in alphabetical order …
=> Refactor risk flags
